version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - promotion
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: cafe
      POSTGRES_USER: expresso
      POSTGRES_DB: promo
    ports:
      - "5432:5432"




networks:
  promotion:


